name = "AbstractLinearOperators"
uuid = "5410e3fe-0e5d-4700-95f7-ee2c7a54c20b"
authors = ["Gabrio Rizzuti <rizzuti.gabrio@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
