name = "AbstractLinearOperators"
uuid = "bb902dec-a34b-4f3c-9707-4856bea60ee0"
authors = ["Gabrio Rizzuti <rizzuti.gabrio@gmail.com>"]
version = "1.0.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
