name = "AbstractLinearOperators"
uuid = "bb902dec-a34b-4f3c-9707-4856bea60ee0"
authors = ["Gabrio Rizzuti <rizzuti.gabrio@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
